### ISSUE TITLE
Actions are failing

### ISSUE THREAD

**Issue by wzieba** [niclin/rails-github-actions-example#7]
Thanks for providing this sample.

I see that since [this](https://github.com/niclin/rails-github-actions-example/commit/dc80d16d140a9d825b10052bcd0c8d5da3e10c15) commit all the actions are failing because of 

```
##[error]Failed to initialize, postgres service is unhealthy.
```

Github Actions changed something and now it's necessary to provide password to Postgres like in samples https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers

This should resolve failing builds.

**Comment by niclin** [comment]
@wzieba Thanks to your report 😄 

it's already resolved failing builds.

https://github.com/niclin/rails-github-actions-example/pull/8
